#!/usr/bin/env bash
# Issue the Raspberry Pi server certificate signed by the station CA
# (ADR-0007 §4). The RPi serves rpi_source_service over TLS using
# this material; the station's GCS client validates against the same
# CA generated by `gen_ca.sh`.

set -euo pipefail

OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/out"
CA_KEY="$OUT_DIR/station-root-ca.key"
CA_CRT="$OUT_DIR/station-root-ca.crt"

if [[ ! -f "$CA_KEY" || ! -f "$CA_CRT" ]]; then
  echo "Run scripts/security/gen_ca.sh first." >&2
  exit 1
fi

CN="${RPI_CN:-rpi.local}"
RPI_HOST="${RPI_HOST:-rpi.local}"
RPI_IP="${RPI_IP:-192.168.4.1}"
DAYS="${RPI_DAYS:-365}"

KEY="$OUT_DIR/rpi-server.key"
CSR="$OUT_DIR/rpi-server.csr"
CRT="$OUT_DIR/rpi-server.crt"
EXT="$OUT_DIR/rpi-server.ext"

cat > "$EXT" <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = $RPI_HOST
DNS.2 = localhost
IP.1  = $RPI_IP
IP.2  = 127.0.0.1
EOF

openssl genrsa -out "$KEY" 2048
openssl req -new -key "$KEY" -subj "/CN=$CN" -out "$CSR"
openssl x509 -req \
  -in "$CSR" \
  -CA "$CA_CRT" -CAkey "$CA_KEY" -CAcreateserial \
  -out "$CRT" \
  -days "$DAYS" \
  -sha256 \
  -extfile "$EXT"

chmod 600 "$KEY"
chmod 644 "$CRT"
rm -f "$CSR" "$EXT"

echo "Created:"
echo "  $CRT"
echo "  $KEY"
echo "Copy *.key/*.crt to RPi: /etc/rescue-ai/rpi-server.{key,crt}"
echo "Copy CA cert to RPi:     /etc/rescue-ai/station-root-ca.crt"
