{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rescue-ai-sync-worker.fullname" . }}-config
  labels:
    {{- include "rescue-ai-sync-worker.labels" . | nindent 4 }}
data:
  DEPLOYMENT_REMOTE_S3_ENDPOINT: {{ .Values.config.remoteS3.endpoint | quote }}
  DEPLOYMENT_REMOTE_S3_REGION: {{ .Values.config.remoteS3.region | quote }}
  DEPLOYMENT_REMOTE_S3_BUCKET: {{ .Values.config.remoteS3.bucket | quote }}
  DEPLOYMENT_SYNC_BATCH_SIZE: {{ .Values.sync.batchSize | quote }}
  DEPLOYMENT_SYNC_INTERVAL_SEC: {{ .Values.sync.intervalSec | quote }}
  DEPLOYMENT_SYNC_MAX_ATTEMPTS: {{ .Values.sync.maxAttempts | quote }}
  DEPLOYMENT_SYNC_PROCESSING_TIMEOUT_SEC: {{ .Values.sync.processingTimeoutSec | quote }}
{{- end }}
