{{- if and .Values.enabled (eq .Values.secrets.source "kube") (not .Values.secrets.kube.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rescue-ai-sync-worker.kubeSecretName" . }}
  labels:
    {{- include "rescue-ai-sync-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.kube.inline }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
